# application.properties
spring.application.name=TrustHelp
server.initialize-data=true

# Conexao Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/thelp
spring.datasource.username=admin_thelp
spring.datasource.password=S3nh4Sup3rS3gur@!2025

jwt.secret=mySuperSecretKeyForTrustHelpApplication2024ThatShouldBeAtLeast32CharactersLong
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer